<template>
    <div id="read-more-component" class="read-more-component">
        <h1>Read More</h1>
        <div class="row">
            <div class="col s12 m6 mo3 center">
                <read-more class="card" :compressed-height="168">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio eos exercitationem dolores. Deserunt odit quod, officiis, aut in, dolore ad voluptas aliquid voluptates pariatur quae laborum. Quos illo expedita ex, sed quisquam porro hic labore, sint excepturi facere. Eligendi dolorum, enim ullam quod minima temporibus, nam quo. Et animi, veniam molestiae. Sunt ex ullam est quaerat commodi molestias. Amet aliquam dicta fugit eaque maxime minima, libero, voluptates quod reiciendis placeat earum maiores. Vitae sed quia quam molestiae quos eaque nobis, consequuntur accusamus est illo explicabo dignissimos qui pariatur laudantium facilis nisi sequi, sunt quod quaerat repudiandae placeat officiis? Aliquid commodi quis dolore quo animi, et, ullam aspernatur totam. Eligendi architecto animi, exercitationem error consectetur. Tempora architecto neque quos reiciendis quod suscipit fuga deleniti temporibus voluptate. Eum adipisci magnam delectus corporis culpa quo voluptate nesciunt eligendi esse ad hic perspiciatis aliquam mollitia, voluptates accusantium officia suscipit quis, distinctio deserunt dolorem quaerat saepe doloremque. Dicta quasi, alias doloribus nesciunt nulla cupiditate! Est reiciendis non, labore, accusantium numquam nobis? Odit excepturi, modi numquam, autem voluptatum ratione doloribus asperiores rem totam commodi at, repudiandae earum fugit reprehenderit quam accusamus esse doloremque ad delectus quae unde quis amet. Velit, earum recusandae ut consequatur, minus laboriosam.</p>
                    <p>Consequatur vitae modi dolore ullam quis asperiores nobis reprehenderit illo quo a ab, minima repellat! Rem, nisi quasi, nam corporis mollitia omnis. Molestiae, ducimus unde, numquam officiis harum provident soluta excepturi. Debitis, alias veritatis tempore delectus suscipit molestias harum aspernatur fugit cupiditate voluptate est, velit, vitae odit vero adipisci dolore aliquam cumque accusantium necessitatibus dolor similique! Quam voluptates excepturi culpa nihil quo asperiores illum nisi laboriosam sunt dolor, velit, distinctio optio minima harum illo esse est quidem nesciunt modi. Beatae aperiam unde ut animi provident, hic nam itaque ipsam quaerat non at dolores neque consectetur assumenda! Fugiat autem reprehenderit consequuntur rem beatae doloremque voluptates modi ut excepturi, delectus iste quos dignissimos inventore velit necessitatibus iusto, blanditiis dolorem, consequatur fugit est soluta libero suscipit esse! Maxime, non, culpa. Consequatur aperiam impedit ipsam nulla quisquam! Eos aspernatur sequi, dolore minus quos nisi maxime beatae at deserunt itaque ex, iure fuga ipsum. Eius ut harum, beatae fugit iure doloremque sint ducimus doloribus quae excepturi minima, vero nisi adipisci iusto tempore dignissimos aspernatur sed! Perferendis obcaecati quos assumenda tenetur quis a iste inventore blanditiis atque quaerat, voluptates nulla ipsa minus ex ea id odit illo sit fugiat voluptate vero voluptatum doloribus delectus. Est, eos!</p>
                    <p>Quidem earum obcaecati deserunt tempore eos nam cumque unde atque aliquid reiciendis, fuga hic cum corrupti animi officia distinctio quas enim veniam, incidunt, autem eligendi illum magni. Porro quos aut quo velit autem laborum ratione rerum nihil dolore sequi cum ipsum modi dolor reprehenderit praesentium quia tempora ut unde aliquid, quod. Veritatis quod quae debitis fuga, repellendus itaque aliquam, similique, obcaecati nihil qui vel hic necessitatibus asperiores accusamus distinctio illo alias iure nesciunt incidunt voluptatum ab! Molestiae quaerat corporis, facilis incidunt cumque eos odit minus adipisci? Distinctio neque dolores officia, modi debitis voluptates consequuntur minus architecto tempore placeat fugiat quam asperiores cupiditate! Fugiat non eum, nisi quisquam voluptate dolor repellendus optio unde magnam dignissimos odio quidem possimus libero inventore quasi quas molestiae esse vero iste doloremque, fugit facere, aspernatur ad! Inventore labore quam ipsa sed tempore cum ducimus ullam modi dicta voluptates necessitatibus hic sunt laborum possimus, culpa ea soluta sequi! Praesentium, excepturi itaque libero repellendus alias ipsa sint totam, aut, fugiat delectus ratione in sequi minima porro maiores soluta mollitia quisquam. Veritatis molestias hic minus praesentium quidem, in sapiente minima nisi sit totam numquam qui velit, quod dolorem maiores dignissimos, temporibus optio officiis eos iste harum fugiat asperiores. Consectetur.</p>
                    <p>Nihil error culpa numquam aspernatur voluptatem optio, expedita sint debitis totam incidunt consectetur. Iste labore officiis, cum fugit architecto vitae, fuga debitis dignissimos et! Ex dolorem eveniet quibusdam ratione assumenda consectetur sapiente doloremque esse quo culpa similique, omnis ducimus sint, reiciendis impedit minima voluptas ab, ipsam nobis. Eveniet hic aperiam a veniam mollitia, aliquid! Facilis, pariatur perferendis ipsum quos doloremque. Voluptatibus rerum similique perferendis eveniet, officiis sequi soluta officia, enim voluptate adipisci ea pariatur laboriosam, exercitationem rem. Totam earum, perspiciatis at nulla autem temporibus harum ullam animi, eius necessitatibus velit repellendus soluta quaerat consequatur ad quo reprehenderit aspernatur. Error ullam nesciunt sunt quibusdam velit ex perferendis perspiciatis, vitae iure mollitia itaque! Itaque id quae nam ipsum dolor, recusandae aliquam similique nulla molestiae, adipisci inventore deserunt voluptatum. Nam, voluptas. Ad exercitationem debitis blanditiis, suscipit fugit quos numquam repellendus architecto delectus iure facilis necessitatibus nam obcaecati enim nulla optio dignissimos inventore ipsum dolorem nisi ipsam a impedit autem eum. Culpa obcaecati, totam aspernatur tempora doloremque rerum unde, dolor corrupti asperiores excepturi expedita adipisci quia iste quo, ut. Temporibus excepturi nesciunt incidunt quae nulla dignissimos et labore minima, assumenda dicta laborum accusamus, veniam eveniet aut eius voluptatum eligendi animi alias reprehenderit perspiciatis architecto!</p>
                    <p>Eaque eos unde at nisi ad cumque ut, animi nam consequuntur, adipisci minus. Adipisci recusandae soluta minus, veniam nihil asperiores ipsum! Sequi consequuntur aperiam quae, autem nihil odit a accusantium mollitia, doloremque. Dolore ullam voluptate, quibusdam non ut facilis odio saepe accusantium, voluptatem aliquam suscipit libero expedita temporibus sint! Earum totam eaque quaerat, perspiciatis adipisci dicta, quas rem in hic pariatur consequatur alias, sed impedit! Facilis quod porro, amet? Voluptates numquam minima dolor fugit placeat mollitia id! Numquam est molestiae corporis natus deserunt laboriosam, sequi hic odio nisi. Explicabo corporis est perferendis nisi, nobis. Esse aliquid, quos amet et nihil corporis nulla doloremque in commodi dicta doloribus itaque, exercitationem quam nostrum eaque praesentium, nobis odio. Quisquam impedit vitae deleniti commodi, expedita repellendus aperiam, quod, eveniet saepe dolorem sapiente deserunt tempora veniam ducimus possimus consequuntur in illum. Consectetur, facilis autem, obcaecati, aliquid velit nam illum inventore at, eaque est modi doloribus quidem eos maxime officiis. Delectus quasi alias natus maiores harum consequuntur ipsam ad incidunt voluptatem quas assumenda vero at cum quibusdam, ipsum, sapiente quae quaerat quidem eligendi possimus qui, voluptatibus beatae laudantium saepe esse! Qui, architecto hic. Aliquam quos quo nostrum porro velit, dolore perferendis assumenda, iure omnis fugit accusamus!</p>
                </read-more>
            </div>
        </div>
    </div>
</template>
<script>
    import ReadMore from 'components/ReadMore';
    export default {
        name: 'ReadMoreComponent',
        components: {
            ReadMore,
        },
    };
</script>
